### ISSUE TITLE
pry-theme try command cannot find themes, despite them existing in theme directory

### ISSUE THREAD

**Issue by kzrbill** [kyrylo/pry-theme#42]
[1] pry(main)> pry-theme try zenburn
Cannot find "zenburn" amongst themes in /Users/xxx/.pry/themes

Theme exists at path /Users/xxx/.pry/themes/zenburn.prytheme.rb

Ruby 2.0.0
pry (0.10.0)
pry-theme (1.1.2)

**Comment by h35514n** [comment]
I've started running into a similar problem for some reason. Pry won't load any color scheme at all except for the default one.

```
~ % ls ~/.pry/themes
railscasts.prytheme.rb  twilight.prytheme.rb
```

```
~ % cat .pryrc
Pry.config.theme = "railscasts"
Pry.config.editor = "subl -wn"

Pry.prompt = [
  proc { |obj, nest_level, _| prompt = ">> " },
  proc { |obj, nest_level, _| prompt = "   " }
]

Pry.config.exception_handler = proc do |output, exception, _|
  output.puts "#{exception.class}: #{exception.message}"
  exception.backtrace.each do |bt|
    puts "\tfrom: #{bt}"
    break if bt =~ /^\(pry\)/
  end
end
```

```
~ % pry
>> PryTheme
=> PryTheme
>> pry-theme try railscasts
Cannot find "railscasts" amongst themes in /Users/puller/.pry/themes
>> pry-theme list

>>
```

```
>> pry-theme current
NoMethodError: undefined method `name' for nil:NilClass
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-theme-1.1.2/lib/pry-theme/commands.rb:147:in `block (2 levels) in def_current'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/slop-3.5.0/lib/slop.rb:260:in `call'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/slop-3.5.0/lib/slop.rb:260:in `parse!'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/slop-3.5.0/lib/slop.rb:235:in `parse!'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/lib/pry/command.rb:576:in `call'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/lib/pry/command.rb:456:in `call_with_hooks'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/lib/pry/command.rb:427:in `call_safely'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/lib/pry/command.rb:369:in `process_line'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/lib/pry/command_set.rb:393:in `process_line'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/lib/pry/pry_instance.rb:402:in `process_command'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/lib/pry/pry_instance.rb:433:in `process_command_safely'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/lib/pry/pry_instance.rb:270:in `handle_line'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/lib/pry/pry_instance.rb:241:in `block (2 levels) in eval'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/lib/pry/pry_instance.rb:240:in `catch'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/lib/pry/pry_instance.rb:240:in `block in eval'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/lib/pry/pry_instance.rb:239:in `catch'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/lib/pry/pry_instance.rb:239:in `eval'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/lib/pry/repl.rb:77:in `block in repl'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/lib/pry/repl.rb:67:in `loop'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/lib/pry/repl.rb:67:in `repl'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/lib/pry/repl.rb:38:in `block in start'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/lib/pry/input_lock.rb:61:in `call'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/lib/pry/input_lock.rb:61:in `__with_ownership'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/lib/pry/input_lock.rb:79:in `with_ownership'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/lib/pry/repl.rb:38:in `start'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/lib/pry/repl.rb:15:in `start'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/lib/pry/pry_class.rb:169:in `start'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/lib/pry/cli.rb:219:in `block in <top (required)>'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/lib/pry/cli.rb:83:in `call'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/lib/pry/cli.rb:83:in `block in parse_options'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/lib/pry/cli.rb:83:in `each'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/lib/pry/cli.rb:83:in `parse_options'
    from: /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pry-0.10.0/bin/pry:16:in `<top (required)>'
    from: /usr/local/var/rbenv/versions/2.1.2/bin/pry:23:in `load'
    from: /usr/local/var/rbenv/versions/2.1.2/bin/pry:23:in `<main>'
>>
```

```
>> PryTheme::ThemeList.current_theme
=> nil
```

```
~ % rbenv version
2.1.2 (set by /usr/local/var/rbenv/version)
~ % gem list | grep pry
pry (0.10.0)
pry-theme (1.1.2)
```
